### ISSUE TITLE
Add support for custom metadata, new `info` and `exists` method

### ISSUE THREAD

**Issue by grdsdev** [supabase/storage-py#295]
**Is your feature request related to a problem? Please describe.**
There are 2 new supported methods that needs to be added.

1. `info(path: str)`
2. `exists(path: str)`

And also the upload methods now support custom metadata to be associated with the uploaded file.

**Additional context**
JS: https://github.com/supabase/storage-js/pull/207
Swift: https://github.com/supabase/supabase-swift/pull/510

**Comment by jppty** [comment]
Is there documentation on how to add metadata through TUS uploads?

The PR here indicates TUS is supported: https://github.com/supabase/storage/pull/518

**Comment by grdsdev** [comment]
Hey @jppty we just started working on the TUS implementation for Python, yet not supported.

This is the PR if you wish to track progress: https://github.com/supabase/storage-py/pull/294

**Comment by jppty** [comment]
My bad - didn't realize this was the python repo. Thanks for the quick response :)
